import {NavBarPrivada} from "@/app/(private)/_components/Navbar"

export const metadata = {
    title: "Seccion privada",
    description: "Generated by create next app",
  };

export default function PrivateLayout({children}){
  return (
    <>
        <NavBarPrivada />
        {children}
    </>
  )
}